//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityBridge2.WebServiceDataSource.Forums {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BriefMessagesContainer", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Com.Forums.Service")]
    [System.SerializableAttribute()]
    public partial class BriefMessagesContainer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CommunityBridge2.WebServiceDataSource.Forums.BriefMessage[] ResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommunityBridge2.WebServiceDataSource.Forums.BriefMessage[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BriefMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Com.Forums.Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CommunityBridge2.WebServiceDataSource.Forums.Message))]
    public partial class BriefMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ArchivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CommunityBridge2.WebServiceDataSource.Forums.BriefUser CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid DiscussionGroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid DiscussionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAbusiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsProposedAnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CommunityBridge2.WebServiceDataSource.Forums.BriefUser ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ModifiedByIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NntpMessageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRepliesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Archived {
            get {
                return this.ArchivedField;
            }
            set {
                if ((this.ArchivedField.Equals(value) != true)) {
                    this.ArchivedField = value;
                    this.RaisePropertyChanged("Archived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentType {
            get {
                return this.ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentTypeField, value) != true)) {
                    this.ContentTypeField = value;
                    this.RaisePropertyChanged("ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommunityBridge2.WebServiceDataSource.Forums.BriefUser CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DiscussionGroupId {
            get {
                return this.DiscussionGroupIdField;
            }
            set {
                if ((this.DiscussionGroupIdField.Equals(value) != true)) {
                    this.DiscussionGroupIdField = value;
                    this.RaisePropertyChanged("DiscussionGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DiscussionId {
            get {
                return this.DiscussionIdField;
            }
            set {
                if ((this.DiscussionIdField.Equals(value) != true)) {
                    this.DiscussionIdField = value;
                    this.RaisePropertyChanged("DiscussionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAbusive {
            get {
                return this.IsAbusiveField;
            }
            set {
                if ((this.IsAbusiveField.Equals(value) != true)) {
                    this.IsAbusiveField = value;
                    this.RaisePropertyChanged("IsAbusive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAnswer {
            get {
                return this.IsAnswerField;
            }
            set {
                if ((this.IsAnswerField.Equals(value) != true)) {
                    this.IsAnswerField = value;
                    this.RaisePropertyChanged("IsAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsProposedAnswer {
            get {
                return this.IsProposedAnswerField;
            }
            set {
                if ((this.IsProposedAnswerField.Equals(value) != true)) {
                    this.IsProposedAnswerField = value;
                    this.RaisePropertyChanged("IsProposedAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommunityBridge2.WebServiceDataSource.Forums.BriefUser ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ModifiedById {
            get {
                return this.ModifiedByIdField;
            }
            set {
                if ((this.ModifiedByIdField.Equals(value) != true)) {
                    this.ModifiedByIdField = value;
                    this.RaisePropertyChanged("ModifiedById");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NntpMessageIndex {
            get {
                return this.NntpMessageIndexField;
            }
            set {
                if ((this.NntpMessageIndexField.Equals(value) != true)) {
                    this.NntpMessageIndexField = value;
                    this.RaisePropertyChanged("NntpMessageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalReplies {
            get {
                return this.TotalRepliesField;
            }
            set {
                if ((this.TotalRepliesField.Equals(value) != true)) {
                    this.TotalRepliesField = value;
                    this.RaisePropertyChanged("TotalReplies");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BriefUser", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Com.Forums.Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CommunityBridge2.WebServiceDataSource.Forums.User))]
    public partial class BriefUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnswersCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAdministratorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsInappropriateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMsftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMvpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime JoinedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastActiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostsCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StarsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnswersCount {
            get {
                return this.AnswersCountField;
            }
            set {
                if ((this.AnswersCountField.Equals(value) != true)) {
                    this.AnswersCountField = value;
                    this.RaisePropertyChanged("AnswersCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdministrator {
            get {
                return this.IsAdministratorField;
            }
            set {
                if ((this.IsAdministratorField.Equals(value) != true)) {
                    this.IsAdministratorField = value;
                    this.RaisePropertyChanged("IsAdministrator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInappropriate {
            get {
                return this.IsInappropriateField;
            }
            set {
                if ((this.IsInappropriateField.Equals(value) != true)) {
                    this.IsInappropriateField = value;
                    this.RaisePropertyChanged("IsInappropriate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMsft {
            get {
                return this.IsMsftField;
            }
            set {
                if ((this.IsMsftField.Equals(value) != true)) {
                    this.IsMsftField = value;
                    this.RaisePropertyChanged("IsMsft");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMvp {
            get {
                return this.IsMvpField;
            }
            set {
                if ((this.IsMvpField.Equals(value) != true)) {
                    this.IsMvpField = value;
                    this.RaisePropertyChanged("IsMvp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime JoinedDate {
            get {
                return this.JoinedDateField;
            }
            set {
                if ((this.JoinedDateField.Equals(value) != true)) {
                    this.JoinedDateField = value;
                    this.RaisePropertyChanged("JoinedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastActiveDate {
            get {
                return this.LastActiveDateField;
            }
            set {
                if ((this.LastActiveDateField.Equals(value) != true)) {
                    this.LastActiveDateField = value;
                    this.RaisePropertyChanged("LastActiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostsCount {
            get {
                return this.PostsCountField;
            }
            set {
                if ((this.PostsCountField.Equals(value) != true)) {
                    this.PostsCountField = value;
                    this.RaisePropertyChanged("PostsCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stars {
            get {
                return this.StarsField;
            }
            set {
                if ((this.StarsField.Equals(value) != true)) {
                    this.StarsField = value;
                    this.RaisePropertyChanged("Stars");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Com.Forums.Service")]
    [System.SerializableAttribute()]
    public partial class Message : CommunityBridge2.WebServiceDataSource.Forums.BriefMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CommunityBridge2.WebServiceDataSource.Forums.MessageHistory[] MessageHistoryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommunityBridge2.WebServiceDataSource.Forums.MessageHistory[] MessageHistory {
            get {
                return this.MessageHistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageHistoryField, value) != true)) {
                    this.MessageHistoryField = value;
                    this.RaisePropertyChanged("MessageHistory");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Com.Forums.Service")]
    [System.SerializableAttribute()]
    public partial class User : CommunityBridge2.WebServiceDataSource.Forums.BriefUser {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CommunityBridge2.WebServiceDataSource.Forums.ForumPermission[] PermissionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommunityBridge2.WebServiceDataSource.Forums.ForumPermission[] Permissions {
            get {
                return this.PermissionsField;
            }
            set {
                if ((object.ReferenceEquals(this.PermissionsField, value) != true)) {
                    this.PermissionsField = value;
                    this.RaisePropertyChanged("Permissions");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForumPermission", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Com.Forums.Service")]
    [System.SerializableAttribute()]
    public partial class ForumPermission : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanMarkAnswersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanPostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanViewAbusiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanViewDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanViewMessageHistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ForumIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAnswererField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsModeratorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOwnerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanMarkAnswers {
            get {
                return this.CanMarkAnswersField;
            }
            set {
                if ((this.CanMarkAnswersField.Equals(value) != true)) {
                    this.CanMarkAnswersField = value;
                    this.RaisePropertyChanged("CanMarkAnswers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanPost {
            get {
                return this.CanPostField;
            }
            set {
                if ((this.CanPostField.Equals(value) != true)) {
                    this.CanPostField = value;
                    this.RaisePropertyChanged("CanPost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanViewAbusive {
            get {
                return this.CanViewAbusiveField;
            }
            set {
                if ((this.CanViewAbusiveField.Equals(value) != true)) {
                    this.CanViewAbusiveField = value;
                    this.RaisePropertyChanged("CanViewAbusive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanViewDeleted {
            get {
                return this.CanViewDeletedField;
            }
            set {
                if ((this.CanViewDeletedField.Equals(value) != true)) {
                    this.CanViewDeletedField = value;
                    this.RaisePropertyChanged("CanViewDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanViewMessageHistory {
            get {
                return this.CanViewMessageHistoryField;
            }
            set {
                if ((this.CanViewMessageHistoryField.Equals(value) != true)) {
                    this.CanViewMessageHistoryField = value;
                    this.RaisePropertyChanged("CanViewMessageHistory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ForumId {
            get {
                return this.ForumIdField;
            }
            set {
                if ((this.ForumIdField.Equals(value) != true)) {
                    this.ForumIdField = value;
                    this.RaisePropertyChanged("ForumId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAnswerer {
            get {
                return this.IsAnswererField;
            }
            set {
                if ((this.IsAnswererField.Equals(value) != true)) {
                    this.IsAnswererField = value;
                    this.RaisePropertyChanged("IsAnswerer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsModerator {
            get {
                return this.IsModeratorField;
            }
            set {
                if ((this.IsModeratorField.Equals(value) != true)) {
                    this.IsModeratorField = value;
                    this.RaisePropertyChanged("IsModerator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOwner {
            get {
                return this.IsOwnerField;
            }
            set {
                if ((this.IsOwnerField.Equals(value) != true)) {
                    this.IsOwnerField = value;
                    this.RaisePropertyChanged("IsOwner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageHistory", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Com.Forums.Service")]
    [System.SerializableAttribute()]
    public partial class MessageHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EditedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid EditorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CommunityBridge2.WebServiceDataSource.Forums.HistoryItemType ItemTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Edited {
            get {
                return this.EditedField;
            }
            set {
                if ((this.EditedField.Equals(value) != true)) {
                    this.EditedField = value;
                    this.RaisePropertyChanged("Edited");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid EditorId {
            get {
                return this.EditorIdField;
            }
            set {
                if ((this.EditorIdField.Equals(value) != true)) {
                    this.EditorIdField = value;
                    this.RaisePropertyChanged("EditorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommunityBridge2.WebServiceDataSource.Forums.HistoryItemType ItemType {
            get {
                return this.ItemTypeField;
            }
            set {
                if ((this.ItemTypeField.Equals(value) != true)) {
                    this.ItemTypeField = value;
                    this.RaisePropertyChanged("ItemType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((this.MessageIdField.Equals(value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryItemType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Com.Forums.Model")]
    public enum HistoryItemType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Edit = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Abusive = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vote = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChangeType = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Split = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Merge = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Move = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Assigned = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProposeAnswer = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnProposeAnswer = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MarkAnswer = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnmarkAnswer = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Undelete = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Escalated = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeEscalated = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RemoveAbusive = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RemoveVote = 17,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForumsContainer", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Com.Forums.Service")]
    [System.SerializableAttribute()]
    public partial class ForumsContainer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CommunityBridge2.WebServiceDataSource.Forums.Forum[] ResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommunityBridge2.WebServiceDataSource.Forums.Forum[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Forum", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Com.Forums.Service")]
    [System.SerializableAttribute()]
    public partial class Forum : CommunityBridge2.WebServiceDataSource.Forums.BriefForum {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CommunityBridge2.WebServiceDataSource.Forums.Announcement[] AnnouncementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CommunityBridge2.WebServiceDataSource.Forums.Category[] CategoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CommunityBridge2.WebServiceDataSource.Forums.ForumFact StatisticsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommunityBridge2.WebServiceDataSource.Forums.Announcement[] Announcements {
            get {
                return this.AnnouncementsField;
            }
            set {
                if ((object.ReferenceEquals(this.AnnouncementsField, value) != true)) {
                    this.AnnouncementsField = value;
                    this.RaisePropertyChanged("Announcements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommunityBridge2.WebServiceDataSource.Forums.Category[] Categories {
            get {
                return this.CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true)) {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedOn {
            get {
                return this.ModifiedOnField;
            }
            set {
                if ((this.ModifiedOnField.Equals(value) != true)) {
                    this.ModifiedOnField = value;
                    this.RaisePropertyChanged("ModifiedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommunityBridge2.WebServiceDataSource.Forums.ForumFact Statistics {
            get {
                return this.StatisticsField;
            }
            set {
                if ((object.ReferenceEquals(this.StatisticsField, value) != true)) {
                    this.StatisticsField = value;
                    this.RaisePropertyChanged("Statistics");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BriefForum", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Com.Forums.Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CommunityBridge2.WebServiceDataSource.Forums.Forum))]
    public partial class BriefForum : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BugTrackingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ForumIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CommunityBridge2.WebServiceDataSource.Forums.DiscussionGroupType GroupTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLockedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrivateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BugTracking {
            get {
                return this.BugTrackingField;
            }
            set {
                if ((this.BugTrackingField.Equals(value) != true)) {
                    this.BugTrackingField = value;
                    this.RaisePropertyChanged("BugTracking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ForumId {
            get {
                return this.ForumIdField;
            }
            set {
                if ((this.ForumIdField.Equals(value) != true)) {
                    this.ForumIdField = value;
                    this.RaisePropertyChanged("ForumId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommunityBridge2.WebServiceDataSource.Forums.DiscussionGroupType GroupType {
            get {
                return this.GroupTypeField;
            }
            set {
                if ((this.GroupTypeField.Equals(value) != true)) {
                    this.GroupTypeField = value;
                    this.RaisePropertyChanged("GroupType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLocked {
            get {
                return this.IsLockedField;
            }
            set {
                if ((this.IsLockedField.Equals(value) != true)) {
                    this.IsLockedField = value;
                    this.RaisePropertyChanged("IsLocked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrivate {
            get {
                return this.IsPrivateField;
            }
            set {
                if ((this.IsPrivateField.Equals(value) != true)) {
                    this.IsPrivateField = value;
                    this.RaisePropertyChanged("IsPrivate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueName {
            get {
                return this.UniqueNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueNameField, value) != true)) {
                    this.UniqueNameField = value;
                    this.RaisePropertyChanged("UniqueName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiscussionGroupType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Forums.Security.Models")]
    public enum DiscussionGroupType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Forum = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ModeratorForum = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PrivateForum = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ModeratorPostingForum = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForumFact", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Com.Forums.Service")]
    [System.SerializableAttribute()]
    public partial class ForumFact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastPostAuthorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastPostDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid LastPostThreadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastPostTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> LastReplyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxNNTPMessageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ModifiedThreadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalAnsweredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalDeletedMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalQuestionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRecentMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRecentThreadsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRecentUsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalThreadsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalUnansweredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalUnassignedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalUsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastPostAuthorName {
            get {
                return this.LastPostAuthorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastPostAuthorNameField, value) != true)) {
                    this.LastPostAuthorNameField = value;
                    this.RaisePropertyChanged("LastPostAuthorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastPostDate {
            get {
                return this.LastPostDateField;
            }
            set {
                if ((this.LastPostDateField.Equals(value) != true)) {
                    this.LastPostDateField = value;
                    this.RaisePropertyChanged("LastPostDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LastPostThreadId {
            get {
                return this.LastPostThreadIdField;
            }
            set {
                if ((this.LastPostThreadIdField.Equals(value) != true)) {
                    this.LastPostThreadIdField = value;
                    this.RaisePropertyChanged("LastPostThreadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastPostTitle {
            get {
                return this.LastPostTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.LastPostTitleField, value) != true)) {
                    this.LastPostTitleField = value;
                    this.RaisePropertyChanged("LastPostTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> LastReplyId {
            get {
                return this.LastReplyIdField;
            }
            set {
                if ((this.LastReplyIdField.Equals(value) != true)) {
                    this.LastReplyIdField = value;
                    this.RaisePropertyChanged("LastReplyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxNNTPMessageIndex {
            get {
                return this.MaxNNTPMessageIndexField;
            }
            set {
                if ((this.MaxNNTPMessageIndexField.Equals(value) != true)) {
                    this.MaxNNTPMessageIndexField = value;
                    this.RaisePropertyChanged("MaxNNTPMessageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedOn {
            get {
                return this.ModifiedOnField;
            }
            set {
                if ((this.ModifiedOnField.Equals(value) != true)) {
                    this.ModifiedOnField = value;
                    this.RaisePropertyChanged("ModifiedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ModifiedThreadId {
            get {
                return this.ModifiedThreadIdField;
            }
            set {
                if ((this.ModifiedThreadIdField.Equals(value) != true)) {
                    this.ModifiedThreadIdField = value;
                    this.RaisePropertyChanged("ModifiedThreadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalAnswered {
            get {
                return this.TotalAnsweredField;
            }
            set {
                if ((this.TotalAnsweredField.Equals(value) != true)) {
                    this.TotalAnsweredField = value;
                    this.RaisePropertyChanged("TotalAnswered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalComments {
            get {
                return this.TotalCommentsField;
            }
            set {
                if ((this.TotalCommentsField.Equals(value) != true)) {
                    this.TotalCommentsField = value;
                    this.RaisePropertyChanged("TotalComments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalDeletedMessages {
            get {
                return this.TotalDeletedMessagesField;
            }
            set {
                if ((this.TotalDeletedMessagesField.Equals(value) != true)) {
                    this.TotalDeletedMessagesField = value;
                    this.RaisePropertyChanged("TotalDeletedMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalMessages {
            get {
                return this.TotalMessagesField;
            }
            set {
                if ((this.TotalMessagesField.Equals(value) != true)) {
                    this.TotalMessagesField = value;
                    this.RaisePropertyChanged("TotalMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalQuestions {
            get {
                return this.TotalQuestionsField;
            }
            set {
                if ((this.TotalQuestionsField.Equals(value) != true)) {
                    this.TotalQuestionsField = value;
                    this.RaisePropertyChanged("TotalQuestions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecentMessages {
            get {
                return this.TotalRecentMessagesField;
            }
            set {
                if ((this.TotalRecentMessagesField.Equals(value) != true)) {
                    this.TotalRecentMessagesField = value;
                    this.RaisePropertyChanged("TotalRecentMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecentThreads {
            get {
                return this.TotalRecentThreadsField;
            }
            set {
                if ((this.TotalRecentThreadsField.Equals(value) != true)) {
                    this.TotalRecentThreadsField = value;
                    this.RaisePropertyChanged("TotalRecentThreads");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecentUsers {
            get {
                return this.TotalRecentUsersField;
            }
            set {
                if ((this.TotalRecentUsersField.Equals(value) != true)) {
                    this.TotalRecentUsersField = value;
                    this.RaisePropertyChanged("TotalRecentUsers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalThreads {
            get {
                return this.TotalThreadsField;
            }
            set {
                if ((this.TotalThreadsField.Equals(value) != true)) {
                    this.TotalThreadsField = value;
                    this.RaisePropertyChanged("TotalThreads");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalUnanswered {
            get {
                return this.TotalUnansweredField;
            }
            set {
                if ((this.TotalUnansweredField.Equals(value) != true)) {
                    this.TotalUnansweredField = value;
                    this.RaisePropertyChanged("TotalUnanswered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalUnassigned {
            get {
                return this.TotalUnassignedField;
            }
            set {
                if ((this.TotalUnassignedField.Equals(value) != true)) {
                    this.TotalUnassignedField = value;
                    this.RaisePropertyChanged("TotalUnassigned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalUsers {
            get {
                return this.TotalUsersField;
            }
            set {
                if ((this.TotalUsersField.Equals(value) != true)) {
                    this.TotalUsersField = value;
                    this.RaisePropertyChanged("TotalUsers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Announcement", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Com.Forums.Service")]
    [System.SerializableAttribute()]
    public partial class Announcement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CommunityBridge2.WebServiceDataSource.Forums.User CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpiresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommunityBridge2.WebServiceDataSource.Forums.User CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Expires {
            get {
                return this.ExpiresField;
            }
            set {
                if ((this.ExpiresField.Equals(value) != true)) {
                    this.ExpiresField = value;
                    this.RaisePropertyChanged("Expires");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Com.Forums.Service")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForumNewsGroupsContainer", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Com.Forums.Service")]
    [System.SerializableAttribute()]
    public partial class ForumNewsGroupsContainer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CommunityBridge2.WebServiceDataSource.Forums.ForumNewsGroup[] ResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommunityBridge2.WebServiceDataSource.Forums.ForumNewsGroup[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForumNewsGroup", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Com.Forums.Service")]
    [System.SerializableAttribute()]
    public partial class ForumNewsGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ForumIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxNNTPMessageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ForumId {
            get {
                return this.ForumIdField;
            }
            set {
                if ((this.ForumIdField.Equals(value) != true)) {
                    this.ForumIdField = value;
                    this.RaisePropertyChanged("ForumId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxNNTPMessageIndex {
            get {
                return this.MaxNNTPMessageIndexField;
            }
            set {
                if ((this.MaxNNTPMessageIndexField.Equals(value) != true)) {
                    this.MaxNNTPMessageIndexField = value;
                    this.RaisePropertyChanged("MaxNNTPMessageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueName {
            get {
                return this.UniqueNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueNameField, value) != true)) {
                    this.UniqueNameField = value;
                    this.RaisePropertyChanged("UniqueName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MonitoredServicesResponse", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.MSCOM.Monitoring")]
    [System.SerializableAttribute()]
    public partial class MonitoredServicesResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ConfigFileEnvironmentNameField;
        
        private int ConfigFileExpirationModuloInMinutesField;
        
        private System.DateTime ConfigFileLastModifiedTimeField;
        
        private System.DateTime ConfigFileNextExpirationTimeField;
        
        private string ConfigFilePathField;
        
        private string ConfigFileProjectNameField;
        
        private string ConfigFileVersionField;
        
        private string CustomInfoField;
        
        private string DatabaseInfoField;
        
        private bool IsHttpsField;
        
        private string RequestContentTypeField;
        
        private string ServicesMachineField;
        
        private string ServicesNameField;
        
        private System.DateTime ServicesTimeField;
        
        private bool SuccessFlagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ConfigFileEnvironmentName {
            get {
                return this.ConfigFileEnvironmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfigFileEnvironmentNameField, value) != true)) {
                    this.ConfigFileEnvironmentNameField = value;
                    this.RaisePropertyChanged("ConfigFileEnvironmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ConfigFileExpirationModuloInMinutes {
            get {
                return this.ConfigFileExpirationModuloInMinutesField;
            }
            set {
                if ((this.ConfigFileExpirationModuloInMinutesField.Equals(value) != true)) {
                    this.ConfigFileExpirationModuloInMinutesField = value;
                    this.RaisePropertyChanged("ConfigFileExpirationModuloInMinutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime ConfigFileLastModifiedTime {
            get {
                return this.ConfigFileLastModifiedTimeField;
            }
            set {
                if ((this.ConfigFileLastModifiedTimeField.Equals(value) != true)) {
                    this.ConfigFileLastModifiedTimeField = value;
                    this.RaisePropertyChanged("ConfigFileLastModifiedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime ConfigFileNextExpirationTime {
            get {
                return this.ConfigFileNextExpirationTimeField;
            }
            set {
                if ((this.ConfigFileNextExpirationTimeField.Equals(value) != true)) {
                    this.ConfigFileNextExpirationTimeField = value;
                    this.RaisePropertyChanged("ConfigFileNextExpirationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ConfigFilePath {
            get {
                return this.ConfigFilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfigFilePathField, value) != true)) {
                    this.ConfigFilePathField = value;
                    this.RaisePropertyChanged("ConfigFilePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ConfigFileProjectName {
            get {
                return this.ConfigFileProjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfigFileProjectNameField, value) != true)) {
                    this.ConfigFileProjectNameField = value;
                    this.RaisePropertyChanged("ConfigFileProjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ConfigFileVersion {
            get {
                return this.ConfigFileVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfigFileVersionField, value) != true)) {
                    this.ConfigFileVersionField = value;
                    this.RaisePropertyChanged("ConfigFileVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomInfo {
            get {
                return this.CustomInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomInfoField, value) != true)) {
                    this.CustomInfoField = value;
                    this.RaisePropertyChanged("CustomInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DatabaseInfo {
            get {
                return this.DatabaseInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.DatabaseInfoField, value) != true)) {
                    this.DatabaseInfoField = value;
                    this.RaisePropertyChanged("DatabaseInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsHttps {
            get {
                return this.IsHttpsField;
            }
            set {
                if ((this.IsHttpsField.Equals(value) != true)) {
                    this.IsHttpsField = value;
                    this.RaisePropertyChanged("IsHttps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RequestContentType {
            get {
                return this.RequestContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestContentTypeField, value) != true)) {
                    this.RequestContentTypeField = value;
                    this.RaisePropertyChanged("RequestContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ServicesMachine {
            get {
                return this.ServicesMachineField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicesMachineField, value) != true)) {
                    this.ServicesMachineField = value;
                    this.RaisePropertyChanged("ServicesMachine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ServicesName {
            get {
                return this.ServicesNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicesNameField, value) != true)) {
                    this.ServicesNameField = value;
                    this.RaisePropertyChanged("ServicesName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime ServicesTime {
            get {
                return this.ServicesTimeField;
            }
            set {
                if ((this.ServicesTimeField.Equals(value) != true)) {
                    this.ServicesTimeField = value;
                    this.RaisePropertyChanged("ServicesTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool SuccessFlag {
            get {
                return this.SuccessFlagField;
            }
            set {
                if ((this.SuccessFlagField.Equals(value) != true)) {
                    this.SuccessFlagField = value;
                    this.RaisePropertyChanged("SuccessFlag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://forums.microsoft.com/service/", ConfigurationName="Forums.IForumsService")]
    public interface IForumsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://forums.microsoft.com/service/IForumsService/GetForumMessagesBriefForNNTP", ReplyAction="http://forums.microsoft.com/service/IForumsService/GetForumMessagesBriefForNNTPRe" +
            "sponse")]
        CommunityBridge2.WebServiceDataSource.Forums.BriefMessagesContainer GetForumMessagesBriefForNNTP(System.Guid forumId, int nntpMessageStartIndex, int nntpMessageEndIndex, bool loadBody);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://forums.microsoft.com/service/IForumsService/CreateQuestionThread", ReplyAction="http://forums.microsoft.com/service/IForumsService/CreateQuestionThreadResponse")]
        System.Guid CreateQuestionThread(System.Guid forumId, string title, string body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://forums.microsoft.com/service/IForumsService/CreateReply", ReplyAction="http://forums.microsoft.com/service/IForumsService/CreateReplyResponse")]
        System.Guid CreateReply(System.Guid forumId, System.Guid threadId, System.Guid postId, string body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://forums.microsoft.com/service/IForumsService/GetActiveBrands", ReplyAction="http://forums.microsoft.com/service/IForumsService/GetActiveBrandsResponse")]
        string[] GetActiveBrands();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://forums.microsoft.com/service/IForumsService/GetActiveLocales", ReplyAction="http://forums.microsoft.com/service/IForumsService/GetActiveLocalesResponse")]
        string[] GetActiveLocales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://forums.microsoft.com/service/IForumsService/GetAllForumsByBrand", ReplyAction="http://forums.microsoft.com/service/IForumsService/GetAllForumsByBrandResponse")]
        CommunityBridge2.WebServiceDataSource.Forums.ForumsContainer GetAllForumsByBrand(string brandName, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://forums.microsoft.com/service/IForumsService/GetAllForumNewsGroupsByBrand", ReplyAction="http://forums.microsoft.com/service/IForumsService/GetAllForumNewsGroupsByBrandRe" +
            "sponse")]
        CommunityBridge2.WebServiceDataSource.Forums.ForumNewsGroupsContainer GetAllForumNewsGroupsByBrand(string brandName, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://forums.microsoft.com/service/IForumsService/GetAllNewForumNewsGroupsByBran" +
            "d", ReplyAction="http://forums.microsoft.com/service/IForumsService/GetAllNewForumNewsGroupsByBran" +
            "dResponse")]
        CommunityBridge2.WebServiceDataSource.Forums.ForumNewsGroupsContainer GetAllNewForumNewsGroupsByBrand(string brandName, int pageIndex, int pageSize, System.DateTime createdSince);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://forums.microsoft.com/service/IForumsService/GetForum", ReplyAction="http://forums.microsoft.com/service/IForumsService/GetForumResponse")]
        CommunityBridge2.WebServiceDataSource.Forums.Forum GetForum(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://forums.microsoft.com/service/IForumsService/GetForumNewsGroup", ReplyAction="http://forums.microsoft.com/service/IForumsService/GetForumNewsGroupResponse")]
        CommunityBridge2.WebServiceDataSource.Forums.ForumNewsGroup GetForumNewsGroup(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://forums.microsoft.com/service/IForumsService/GetForumNewsGroupByName", ReplyAction="http://forums.microsoft.com/service/IForumsService/GetForumNewsGroupByNameRespons" +
            "e")]
        CommunityBridge2.WebServiceDataSource.Forums.ForumNewsGroup GetForumNewsGroupByName(string discussionGroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://forums.microsoft.com/service/IForumsService/GetStartingMessageIndexForNNTP" +
            "", ReplyAction="http://forums.microsoft.com/service/IForumsService/GetStartingMessageIndexForNNTP" +
            "Response")]
        int GetStartingMessageIndexForNNTP(System.Guid forumId, System.DateTime startingDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://forums.microsoft.com/service/IForumsService/GetMessage", ReplyAction="http://forums.microsoft.com/service/IForumsService/GetMessageResponse")]
        CommunityBridge2.WebServiceDataSource.Forums.Message GetMessage(System.Guid forumId, System.Guid messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://forums.microsoft.com/service/IForumsService/Ping", ReplyAction="http://forums.microsoft.com/service/IForumsService/PingResponse")]
        bool Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://forums.microsoft.com/service/IForumsService/PingMonitoredService", ReplyAction="http://forums.microsoft.com/service/IForumsService/PingMonitoredServiceResponse")]
        CommunityBridge2.WebServiceDataSource.Forums.MonitoredServicesResponse PingMonitoredService(int pingLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://forums.microsoft.com/service/IForumsService/GetMaxReturnPageSize", ReplyAction="http://forums.microsoft.com/service/IForumsService/GetMaxReturnPageSizeResponse")]
        int GetMaxReturnPageSize();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://forums.microsoft.com/service/IForumsService/GetForumMessagesBrief", ReplyAction="http://forums.microsoft.com/service/IForumsService/GetForumMessagesBriefResponse")]
        CommunityBridge2.WebServiceDataSource.Forums.BriefMessagesContainer GetForumMessagesBrief(System.Guid forumId, int pageIndex, int pageSize, bool loadBody);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IForumsServiceChannel : CommunityBridge2.WebServiceDataSource.Forums.IForumsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ForumsServiceClient : System.ServiceModel.ClientBase<CommunityBridge2.WebServiceDataSource.Forums.IForumsService>, CommunityBridge2.WebServiceDataSource.Forums.IForumsService {
        
        public ForumsServiceClient() {
        }
        
        public ForumsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ForumsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForumsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForumsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CommunityBridge2.WebServiceDataSource.Forums.BriefMessagesContainer GetForumMessagesBriefForNNTP(System.Guid forumId, int nntpMessageStartIndex, int nntpMessageEndIndex, bool loadBody) {
            return base.Channel.GetForumMessagesBriefForNNTP(forumId, nntpMessageStartIndex, nntpMessageEndIndex, loadBody);
        }
        
        public System.Guid CreateQuestionThread(System.Guid forumId, string title, string body) {
            return base.Channel.CreateQuestionThread(forumId, title, body);
        }
        
        public System.Guid CreateReply(System.Guid forumId, System.Guid threadId, System.Guid postId, string body) {
            return base.Channel.CreateReply(forumId, threadId, postId, body);
        }
        
        public string[] GetActiveBrands() {
            return base.Channel.GetActiveBrands();
        }
        
        public string[] GetActiveLocales() {
            return base.Channel.GetActiveLocales();
        }
        
        public CommunityBridge2.WebServiceDataSource.Forums.ForumsContainer GetAllForumsByBrand(string brandName, int pageIndex, int pageSize) {
            return base.Channel.GetAllForumsByBrand(brandName, pageIndex, pageSize);
        }
        
        public CommunityBridge2.WebServiceDataSource.Forums.ForumNewsGroupsContainer GetAllForumNewsGroupsByBrand(string brandName, int pageIndex, int pageSize) {
            return base.Channel.GetAllForumNewsGroupsByBrand(brandName, pageIndex, pageSize);
        }
        
        public CommunityBridge2.WebServiceDataSource.Forums.ForumNewsGroupsContainer GetAllNewForumNewsGroupsByBrand(string brandName, int pageIndex, int pageSize, System.DateTime createdSince) {
            return base.Channel.GetAllNewForumNewsGroupsByBrand(brandName, pageIndex, pageSize, createdSince);
        }
        
        public CommunityBridge2.WebServiceDataSource.Forums.Forum GetForum(System.Guid id) {
            return base.Channel.GetForum(id);
        }
        
        public CommunityBridge2.WebServiceDataSource.Forums.ForumNewsGroup GetForumNewsGroup(System.Guid id) {
            return base.Channel.GetForumNewsGroup(id);
        }
        
        public CommunityBridge2.WebServiceDataSource.Forums.ForumNewsGroup GetForumNewsGroupByName(string discussionGroupName) {
            return base.Channel.GetForumNewsGroupByName(discussionGroupName);
        }
        
        public int GetStartingMessageIndexForNNTP(System.Guid forumId, System.DateTime startingDate) {
            return base.Channel.GetStartingMessageIndexForNNTP(forumId, startingDate);
        }
        
        public CommunityBridge2.WebServiceDataSource.Forums.Message GetMessage(System.Guid forumId, System.Guid messageId) {
            return base.Channel.GetMessage(forumId, messageId);
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
        
        public CommunityBridge2.WebServiceDataSource.Forums.MonitoredServicesResponse PingMonitoredService(int pingLevel) {
            return base.Channel.PingMonitoredService(pingLevel);
        }
        
        public int GetMaxReturnPageSize() {
            return base.Channel.GetMaxReturnPageSize();
        }
        
        public CommunityBridge2.WebServiceDataSource.Forums.BriefMessagesContainer GetForumMessagesBrief(System.Guid forumId, int pageIndex, int pageSize, bool loadBody) {
            return base.Channel.GetForumMessagesBrief(forumId, pageIndex, pageSize, loadBody);
        }
    }
}
